### ISSUE TITLE
Ignore directory and all nested directories/files

### ISSUE THREAD

**Issue by markreg** [pilu/fresh#50]
Adding a directory to the `ignored` list does not make `fresh` ignore all nested directories/files.

**Comment by wubin1989** [comment]
Yes, I found the same problem. Anyone can help to fix it?

**Comment by drKnoxy** [comment]
ugh

**Comment by gmccue** [comment]
@wubin1989 are you using a proper `recompile.conf` file? I had the same issue, but it seems to be resolved after setting the proper `root` and `ignore` lines in `recompile.conf`. 

My `recompile.conf` file for reference:
```
root:              .
tmp_path:          .tmp_build
build_name:        my-app
build_log:         my-app-build-errors.log
valid_ext:         .go, .tmpl
ignored:           assets, node_modules, vendor, vm, wraith
build_delay:       600
colors:            1
log_color_main:    cyan
log_color_build:   yellow
log_color_runner:  green
log_color_watcher: magenta
```

I start the binary with the following command within a Docker container:
```
backend:
  build: ./backend
  container_name: backend
  working_dir: /go/src/github.com/my-org/my-project
  command: fresh -c /go/src/github.com/my-org/my-project/containers/backend/recompile.conf
  env_file: ../../.env
  volumes:
   - ../../.:/go/src/github.com/my-org/my-project
  ports:
   - "8000:3001"
  links:
   - cache
```
